### ISSUE TITLE
一个Activity注解多个ViewModel时只初始化了其中一个

### ISSUE THREAD

**Issue by z2wenfa** [hyzhan43/KtArmor-MVVM#1]
# MvmActivityDelegateImpl

private fun initViewModel() {
        activity.javaClass.fields
                .filter { it.isAnnotationPresent(BindViewModel::class.java) }
                .getOrNull(0)
                ?.apply {
                    isAccessible = true
                    set(activity, getViewModel(this))
                }
    }

**Comment by hyzhan43** [comment]
好的，谢谢你的提醒，后续我加上。
