### ISSUE TITLE
FragmentStateAdapter 抓不到

### ISSUE THREAD

**Issue by PascalTang** [hyzhan43/KtArmor-MVVM#2]
在FragmentStateAdapter 內
我的view model inject 抓不到
會一直是null

**Comment by hyzhan43** [comment]
你好，在 Fragment或Activity 中，并且实现列 IMvmFragment 或 IMvmActivity  才会反射注入 viewModel 。  什么场景下 会在 FragmentStateAdapter  用到 viewModel 呢？
