### ISSUE TITLE
内存泄漏的问题

### ISSUE THREAD

**Issue by z2wenfa** [hyzhan43/KtArmor-MVVM#4]
#MvmActivityDelegateImpl

private val iMvmActivity = activity as IMvmActivity //这里强引用了Activity

#ActivityLifecycle 

//缓存了MvmActivityDelegateImpl
private val cache by lazy { LruCache<String, ActivityDelegate>(Setting.ACTIVITY_CACHE_SIZE) } 

    override fun onActivityDestroyed(activity: Activity?) {
        activity?.let { ActivityManager.remove(it) }

        fetchActivityDelegate(activity)?.onDestroy()
    }

Activity调用**onDestory()**后还是被强引用着导致内存泄漏,可以加个LeakCanary看看这类问题

**Comment by hyzhan43** [comment]
好的。谢谢你的提醒，已经修复。
