### ISSUE TITLE
Jetpack + 协程

### ISSUE THREAD

**Issue by junchenChow** [hyzhan43/KtArmor-MVVM#5]
你好~，这个模式很不错感觉，有一点疑惑是注解部分用的反射，个人感觉改成依赖注入 类似dagger2这种会更好一点

**Comment by hyzhan43** [comment]
好的，谢谢你的提议。相比Dagger2，Kotlin语言，个人倾向 采用 Koin 框架会适合些。后续会集成进来，也欢迎你 Pull requests ~
