### ISSUE TITLE
CommonLiveData类中isException()方法判断条件会过时，造成结果返回异常

### ISSUE THREAD

**Issue by 632610503** [hyzhan43/KtArmor-MVVM#7]
复现步骤：
      1.模拟网络请求失败(eg:关闭网络)，这时调用onException(),正常
      2.排除异常情况（**保持LiveData的状态**），正常请求网络，返回失败的结果（KResopnse.isSuccess() = false）,这里应该调用onFailure(),**但是会调用onException()**

出现问题的原因在ActivityActuator中:
    

` errorLiveData.observe(owner, Observer {

                if (isException()) {
                    exceptionBlock(CustomException.handleException(exception!!))
                } else {
                    failureBlock(failureMessage)
                }
            })`

CommonLiveData在第一次请求异常的时候保存了exception，所以isException() = true

 `fun isException(): Boolean {
        return exception != null 
    }`

第二次请求返回失败的结果在DefaultLiveDataActuator中

`override fun <R> failure(liveData: CommonLiveData<R>, message: String?) {
        liveData.failureMessage = message
    }
`

并没有重置exception,所以isException()=true，不会调用failureBlock(failureMessage),而是调用   exceptionBlock(CustomException.handleException(exception!!))

这里应该在新的failureMessage被赋值的时候判断与当前异常是否冲突，然后重置异常状态

`  var failureMessage: String? = ""
        set(value) {
            field = value
            errorLiveData.value = value
            _if(value == exception?.message){
                exception = null
            }_
        }`

或者

` fun isException(): Boolean {
        return exception != null && 
         (exception!!.message == errorLiveData.value ||
          errorLiveData.value == Const.UNKNOWN_ERROR)
    }`

**Comment by hyzhan43** [comment]
非常感谢能提供这么完整的复现过程。可见你很认真看过这个框架，很开心，并且还给出了相应的建议。非常感谢。点赞👍     已经修复并上传了。谢谢你～
