### ISSUE TITLE
一个Activity下加载Viewpager里面三个framgent,里面的viewmodel注解是空的

### ISSUE THREAD

**Issue by s3hengwu** [hyzhan43/KtArmor-MVVM#9]
Activity(实现了IMvmActivity)viewPager+FragmentPagerAdapter+framgent(实现IMvmFragment)，这种情况下fragment里面的注解viewModel是null

**Comment by hyzhan43** [comment]
你好，我按照你说明的例子，尝试了下（源码 Welcome Demo 示例）, viewModel 是正常注入的。
是否是你的 viewModel 类没有继承  BaseViewModel 咧？ 如不是可以麻烦你在详细说明一下吗？

**Comment by hyzhan43** [comment]
已经修复。可以更新至最新版本 v1.1.1
